In [8]:
import numpy as np

# Creating `ndarray`

Use `np.array` to create Numpy array from Python's list.

In [13]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [
    [1, 2, 3, 4],
    [5, 6, 7, 8]
]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

You can inspect the number of dimensions, shapes and type of the `ndarray`:

In [15]:
{
    'shape': arr1.shape,
    'ndim': arr1.ndim,
    'dtype': arr1.dtype
}

{'shape': (5,), 'ndim': 1, 'dtype': dtype('float64')}

In [17]:
{
    'shape': arr2.shape,
    'ndim': arr2.ndim,
    'dtype': arr2.dtype
}

{'shape': (2, 4), 'ndim': 2, 'dtype': dtype('int64')}

# Data Types for `ndarray`
`ndarray` are assumed to be integer (`np.int64`) or float (`np.float64`) by default. You can specify an explicit type for the `ndarray`:

In [24]:
arr1 = np.array(data1, dtype=np.float16)
arr1

array([6. , 7.5, 8. , 0. , 1. ], dtype=float16)

You can convert the array from one type to another with `astype`:

In [23]:
arr2 = arr1.astype(np.int32)
arr2

array([6, 7, 8, 0, 1], dtype=int32)

# Filtering `ndarray`

In [26]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.array(np.random.randn(7,4))
data

array([[ 0.34151759, -2.09853882,  0.51341771, -0.28304358],
       [-0.0330055 ,  1.11031466, -0.57558594,  0.45829112],
       [-1.9689507 , -1.14386649,  1.41271127, -1.24406141],
       [-0.00550861,  0.41467637, -1.88383697, -0.51495712],
       [-0.4676403 , -0.10798843,  0.70818632,  1.41430653],
       [ 0.69193329, -1.02945603, -2.05393854, -0.28591634],
       [ 0.29389069,  0.42956376,  0.4755364 ,  0.40795506]])

Assuming each row correspond to a name. Select all rows that correspond to "Bob":

In [27]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [28]:
data[names == 'Bob']

array([[ 0.34151759, -2.09853882,  0.51341771, -0.28304358],
       [-0.00550861,  0.41467637, -1.88383697, -0.51495712]])

You can combine filtering with slices, integer or list of integers for more precise targeting:

In [29]:
data[names == 'Bob', 2:]

array([[ 0.51341771, -0.28304358],
       [-1.88383697, -0.51495712]])

In [30]:
data[names == 'Bob', 3]

array([-0.28304358, -0.51495712])

In [32]:
data[names == 'Bob', [0, 2]]

array([ 0.34151759, -1.88383697])

To elect everything except `Bob`:

In [34]:
data[names != 'Bob']

array([[-0.0330055 ,  1.11031466, -0.57558594,  0.45829112],
       [-1.9689507 , -1.14386649,  1.41271127, -1.24406141],
       [-0.4676403 , -0.10798843,  0.70818632,  1.41430653],
       [ 0.69193329, -1.02945603, -2.05393854, -0.28591634],
       [ 0.29389069,  0.42956376,  0.4755364 ,  0.40795506]])

In [35]:
data[~(names == 'Bob')]

array([[-0.0330055 ,  1.11031466, -0.57558594,  0.45829112],
       [-1.9689507 , -1.14386649,  1.41271127, -1.24406141],
       [-0.4676403 , -0.10798843,  0.70818632,  1.41430653],
       [ 0.69193329, -1.02945603, -2.05393854, -0.28591634],
       [ 0.29389069,  0.42956376,  0.4755364 ,  0.40795506]])

In [38]:
condition = names == 'Bob'

# Select all Bob
data[condition]

array([[ 0.34151759, -2.09853882,  0.51341771, -0.28304358],
       [-0.00550861,  0.41467637, -1.88383697, -0.51495712]])

In [39]:
# Select everything except Bob
data[~condition]

array([[-0.0330055 ,  1.11031466, -0.57558594,  0.45829112],
       [-1.9689507 , -1.14386649,  1.41271127, -1.24406141],
       [-0.4676403 , -0.10798843,  0.70818632,  1.41430653],
       [ 0.69193329, -1.02945603, -2.05393854, -0.28591634],
       [ 0.29389069,  0.42956376,  0.4755364 ,  0.40795506]])

Conbine conditions with `|` and `&` (yes, the bitwise operators)

In [42]:
condition = (names == 'Bob') | (names == 'Will')
data[condition]

array([[ 0.34151759, -2.09853882,  0.51341771, -0.28304358],
       [-1.9689507 , -1.14386649,  1.41271127, -1.24406141],
       [-0.00550861,  0.41467637, -1.88383697, -0.51495712],
       [-0.4676403 , -0.10798843,  0.70818632,  1.41430653]])